### ISSUE TITLE
bridge was generated with only 1 block. No levitation potions has been found on floor.

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/powered-pixel-dungeon#38]
![Screenshot_20200901-211824.png](https://user-images.githubusercontent.com/69046303/91891203-46c9c080-ec99-11ea-9e00-3c34e8908196.png)

**Comment by Smujb** [comment]
Do you have the seed? If the game is still active, press and hold the hero icon on the "load game" window for debug info.

**Comment by Smujb** [comment]
Since I have no seed, this is for an old version, and I haven't been able to reproduce, I'm closing this issue. If you can provide a seed and I can reproduce or you can reproduce this bug on the latest update, I will reopen.
