### ISSUE TITLE
UX issues when using multiple weapons with different reach

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#43]
Sometimes option to attach at a distance is present, sometimes it is not. I don't know remember if it affects gameplay, but it certainly requires more taps e.g. when doing fishing from safe distance.

**Comment by vi** [comment]
Even if I press the wait button, long-reaching weapon still not gets available until I attack at a short range.

I think it should be possible to temporarily ignore the short-reach weapon and use only long-reach one, maybe by alternating "attack" and "wait" buttons.

**Comment by Smujb** [comment]
Addressed by: https://github.com/Smujb/powered-pixel-dungeon/commit/440c561cc239efdfda96d08e19ace85ab013bc66
