### ISSUE TITLE
Death when diving out looks strange.

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#44]
* Map is undiscovered (it was partially visible before)
* Not on top of deep water
* No "Game over" text (it has probably blinked though in the water level).
* No loot (it has probably remained in the water)

![underwater2](https://user-images.githubusercontent.com/173219/94350386-885e4900-0056-11eb-81f3-cd7346f2afb5.png)

commit 01c7b741d1c8981a89f912d79427a1d05bbbaa93

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/powered-pixel-dungeon/commit/4cb36f5c5320f14754de67d976a7a4a0e5a2fc8b
