### ISSUE TITLE
Is grass supposed to grow underwater?

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#45]
Are blooming weapons supposed to bloom underwater?

![underwater1](https://user-images.githubusercontent.com/173219/94350416-c5c2d680-0056-11eb-9c45-788f9eb7ddbd.png)

commit 01c7b741d1c8981a89f912d79427a1d05bbbaa93

**Comment by Smujb** [comment]
https://github.com/Smujb/powered-pixel-dungeon/commit/f10f9698d425884f5a5c5d0e44f2c0986e2bd339
