### ISSUE TITLE
Navigation though level is annoyingly interrupted by enemies chaotically phasing in and out of perception 

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#46]
This leads to much more clicks to walk to distant room, as you need to reconfirm movement again and again compared to Shattered.

Typically when hero becomes aware of an enemy in Shattered, he/she need to do something with it, so unconditional interruption is usually granted. In Powered it is much often that the hero needs to just ignore it for the time being.

Ideas about UX improvement:

* Second tap to continue walking at the same destination should temporarily add currently visible enemies into an ignorelist. If an enemy from the ignorelist becomes imperceptible, then perceptible again, it does not interrupt the walk. Ignorelist is cleared when you arrive at the destination.
* Sleeping enemies that are behind a wall and cannot be attacked are just always ignored (once they are shown once). A unhighlighted "hero's memory" mark can be shown on map to avoid this leading to missing occasional advantage of knowing about an enemy in advance.

commit 01c7b741d1c8981a89f912d79427a1d05bbbaa93

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/powered-pixel-dungeon/commit/bd1964320d44db6664a3ee86e4b75e7cfd61afde. When moving, the hero will not be interrupted by mobs not in direct line of sight, but will still detect mobs through walls.
