### ISSUE TITLE
Description text is often wrong.

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#47]
* Rogue garb (and probably mage's robe) is still "null".
* "The Rogue starts with a unique artifact: the Cloack of Shadows" - looks no longer relevant.
* Once when I loaded an old savefile, it showed that mage has a Greatsword imbued with Wand of Breath Sentry (and it had the sword's sprite). I cannot reproduce it anymore (even when loading the same savefile). I also immeidately exited, so no screenshot or behaviour. Probably it's some saving/restoring issue.
* I saw in commit messages that magical protection is supposed to be somehow linked woth Focus. But description of Focus only mentions wands - is it up to date?
* Hero got a sword named "Weapon".

commit 01c7b741d1c8981a89f912d79427a1d05bbbaa93

**Comment by Smujb** [comment]
> I saw in commit messages that magical protection is supposed to be somehow linked woth Focus. But description of Focus only mentions wands - is it up to date?

That was briefly the case but was reverted with armour rework

> Once when I loaded an old savefile, it showed that mage has a Greatsword imbued with Wand of Breath Sentry (and it had the sword's sprite). I cannot reproduce it anymore (even when loading the same savefile). I also immeidately exited, so no screenshot or behaviour. Probably it's some saving/restoring issue.

> Hero got a sword named "Weapon".

> Rogue garb (and probably mage's robe) is still "null".

Gotta fix that yes

> "The Rogue starts with a unique artifact: the Cloack of Shadows" - looks no longer relevant.
Fixed indev

**Comment by Smujb** [comment]
Finally fixed this: https://github.com/Smujb/powered-pixel-dungeon/commit/a2ef514a8112c25e8ab97106143fdbe0c3943c61
