### ISSUE TITLE
Wand charge counter disappears from quickslot when the wand is equipped after clicking on quickslot

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#48]
UI issue.

For example, there are two identified wands, only one of which is typically equipped. Normally I expect both wands to show charge counter in quickslot.

But when I click on unequipped wand's quickslot and choose the other wand to be unequipped, the counter for newly equipped wand disappears.

**Comment by Smujb** [comment]
Equipping wands from quickslot is buggy anyway, I'm removing it

**Comment by vi** [comment]
How many taps would be required to alternate wands competing over one equipment slot after such removal?

**Comment by Smujb** [comment]
You need to go into the inventory to equip them. The reason for this bug is probably that items have to specify whether the quickslot uses targeting. Wands do. This causes bugs when the quick slotted action doesn't use targeting.
