### ISSUE TITLE
Bronze door image still looks teared

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#50]
![shear](https://user-images.githubusercontent.com/173219/94609065-fef18580-02a6-11eb-9e56-965ecb11ccb0.png)

commit 01c7b741d1c8981a89f912d79427a1d05bbbaa93

As usual, seemingly non-tile-aligned square of pixels gets shifted back into its intended place when hero unlocks the door. Also the glitch seems to be broze-door-exclusive - I never saw it with other images.

**Comment by Smujb** [comment]
Yep, it's exclusive to Bronze Doors in the Prison. Nowhere else with nothing else. Lol

Fixed by: https://github.com/Smujb/powered-pixel-dungeon/commit/40a73ce315ed13eaff7bc9442b2a80de33dfc890
