### ISSUE TITLE
Morale loss even when drunk

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#51]
It's hard to get back to normal morale level once it dips below 30%.

Beverages are now weak and it seems that hunger (and maybe even battles) cause morale to still drop even when drunk.

Is it indented and expected?

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/powered-pixel-dungeon/commit/74452517f8861806bb325e0b45bf400e7d95d1c7
