### ISSUE TITLE
Each dark gold ore piece is collected twice

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#52]
At least when Pickaxe is activated from a quickslot, it shows dark ore collecting animation twice and obtains two dark ore items.

It deviates from Shattered. Is it intended/expected?

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/powered-pixel-dungeon/commit/ebee67f600dd8828232054afa0a091992f900ae4
