### ISSUE TITLE
Power Pylon is still glitched

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#53]
![pylon](https://user-images.githubusercontent.com/173219/94993766-ed0c2d00-059b-11eb-8562-de1968cbb747.png)

That game session cannot progress; the savefile is waiting for a fix to arrive.

**Comment by vi** [comment]
In a newly started savefile it does not work as well.

Fortunately, there was a wand that time, so the game progressed.

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/powered-pixel-dungeon/commit/2acfd1d4603a177849f0318207276e4e4c588910
