### ISSUE TITLE
Shall more things that restore health also restore morale?

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#54]
Examples:

* Well of health. I assumed it just restores everything, found out morale is excluded.
* "Well fed" buff. Shall it grant faster morale regen, like it generates health regen? Food items and morale are connected by morale loss from hunger, so it should be logical that satiety is connected to good morale as well.

**Comment by Smujb** [comment]
Addressed by this change: https://github.com/Smujb/powered-pixel-dungeon/commit/9dd69c0d4c4dda80ce93e03867ff1b252310820a
