### ISSUE TITLE
Is this battle with 4-th level boss going OK?

### ISSUE THREAD

**Issue by vi** [Smujb/powered-pixel-dungeon#63]
A run was OK until the king.

![1](https://user-images.githubusercontent.com/173219/97494965-20ae5d00-1978-11eb-9d27-daf963aac4ec.png)

It would be the end of it if there were no Scroll of Retribution. It proved to be super effective:

![2](https://user-images.githubusercontent.com/173219/97495073-49365700-1978-11eb-8cd6-f6d462570f25.png)

Three levels up + about 16k gold is much more than a typical boss win.

---

Was this battle bugged? I don't remember such a stampede in Shattered. And there were almost no monks/warlocks and final phase looked skipped.

commit c48580e994fedf45fb992aa1dd0a2bd284740f07, but the game was started at probably at about f50de264c5d14666ee16311f9961603f01fbc2e7.

**Comment by vi** [comment]
Corollary issue: if you gain multiple levels in one move, it shows multiple talent spending dialogue windows. Additional windows need contain stale data and need to be closed before returning to the main screen.

**Comment by Smujb** [comment]
Fixed by: https://github.com/Smujb/powered-pixel-dungeon/commit/fe13e65b56a4ffd86251e376b93b345a8b2a0c5f
