### ISSUE TITLE
You can't transmute dragon pendants

### ISSUE THREAD

**Issue by Gammalolman** [Smujb/powered-pixel-dungeon#67]
![Screenshot_20201101_160349_com smujamesb cursedpixeldungeon indev](https://user-images.githubusercontent.com/63963512/97806479-13d18800-1c5c-11eb-9d8f-6fecbac7595b.jpg)
Using transmutation scrolls ignores dragon pendants.... And considering you can't equip two of the same one..... You basically are unable to do anything with it.

**Comment by Smujb** [comment]
Post on the Cursed PD Github, this is Powered
